version: "3.8"
services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - 5432:5432
    volumes:
      - boilerplate-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: system
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: rarespecies

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  boilerplate-db: